### PR TITLE
🔧 Remove force unwraps for safe decoding

### PR DESCRIPTION
**Pull request by sasha-myshkina**
To have safe decoding in production, removing force unwraps in `SeatingChart` and `SeatsioWebView`
Logic is not changed.

### CODE REVIEW

**Comment by mroloux** [comment]
Thanks. What exactly does this PR fix? What do you mean by "safe decoding"?

**Comment by sasha-myshkina** [comment]
> Thanks. What exactly does this PR fix? What do you mean by "safe decoding"?

hey! I've replaced force unwrapping, because every `"!"` means a potential crash for the app. Instead, in Swift, we can use `guard` statements and optional chaining to eliminate potential consequences. It'd be generally safer to avoid implicit unwrapping here.

**Comment by sasha-myshkina** [comment]
> Thanks. What exactly does this PR fix? What do you mean by "safe decoding"?

hey @mroloux what do you guys think about it? do you have any particular concerns?

**Comment by mroloux** [comment]
Hi,

I think it's a great idea to not make the app crash when there's an error. However, I would not just swallow the error - at least it should be logged somewhere.

**Comment by mroloux** [comment]
I'm closing this PR for now. Feel free to reopen if you have any updates.

**Pull request closed without merging**
