### PR TITLE
🔧 Add public inits for Labels and SeatsioObject

### PR DESCRIPTION
**Pull request by sasha-myshkina**
This PR introduces more public inits for objects:

- adding public init for `Labels`
- adding public inits for  `SeatsioObject` including `public init(from decoder: Decoder)` to avoid type mismatch error. The error was caught in `extraData`. Since it's an arbitrary payload in JavaScript, adding error handling with `try?`
- conforming `SeatsioObject` to the `Equatable` protocol to be able to compare objects by their `id`s

### CODE REVIEW

**Comment by mroloux** [comment]
Hi,

Thanks for this PR.

Why exactly is the `init` method on `SeatsioObject` needed? Not saying it's wrong, but I'm not an iOS expert 😆

**Comment by sasha-myshkina** [comment]
> Hi,
> 
> Thanks for this PR.
> 
> Why exactly is the `init` method on `SeatsioObject` needed? Not saying it's wrong, but I'm not an iOS expert 😆

Hi!

The first init with `decoder` is there to avoid type mismatch error in `extraData` (using `try?`). It's convenient to have the second init too to mock data when writing tests.

**Comment by mroloux** [comment]
Turns out that `extraData` wasn't properly converted from JSON. I see no easy way of making this work, so I removed the `extraData` property for now. That means we don't need a custom `init` method that takes a `decoder`.

And are the other `init` methods really needed? You mentioned you use them for mocks. But if I understand correctly, you can instantiate a struct even without an `init` method: https://www.logilax.com/swift-struct-init/

**Comment by sasha-myshkina** [comment]
> Turns out that `extraData` wasn't properly converted from JSON. I see no easy way of making this work, so I removed the `extraData` property for now. That means we don't need a custom `init` method that takes a `decoder`.
> 
> And are the other `init` methods really needed? You mentioned you use them for mocks. But if I understand correctly, you can instantiate a struct even without an `init` method: https://www.logilax.com/swift-struct-init/

yeah thanks, removing init with decoder then. Inits for structs are available by default, that's true. However, to use it outside the library init should be declared `public`, and it's something that is not available by default

**Review by mroloux — APPROVED** [review]

**Pull request merged**
